### Get information
GET  http://localhost:1234/

### Get information from products
GET  http://localhost:1234/productos

### Get information from products id
GET  http://localhost:1234/productos/2fd6203c-e0ff-4c71-8274-248a98592f46

### Post new product
POST  http://localhost:1234/productos
Content-Type: application/json

{
     "name": "Recipiente de 40 kg",
     "image": {
        "url": "url",
        "alt": "alt"
     },
    "weight": "40 kg"
}

### Update a specific part of a product
PATCH  http://localhost:1234/productos/2fd6203c-e0ff-4c71-8274-248a98592f46
Content-Type: application/json

{
     "name": "Recipiente de 25 kg",    
    "weight": "250"
}

### Delete a product
DELETE  http://localhost:1234/productos/2fd6203c-e0ff-4c71-8274-248a98592f46